---
name: the-snip
version: 0.0.0.1
github: RobertFischer/the-snip
license: BSD3
author: Robert Fischer
maintainer: smokejumperit@gmail.com
copyright: Copyright (c) 2022 Robert Fischer

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis: Command line tool for extracting demarcated snippets from text files.
category: Tool

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/robertfischer/the-snip#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - attoparsec
  - bytestring
  - path
  - path-io
  - text
  - unix

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Werror=incomplete-record-updates
  - -Werror=incomplete-uni-patterns
  - -Werror=missing-exported-signatures
  - -Werror=missing-fields
  - -Werror=partial-fields
  - -Werror=unused-do-bind
  - -Werror=warnings-deprecations
  - -Widentities
  - -Wmissed-specializations
  - -Wnoncanonical-monad-instances
  - -Wredundant-constraints
  - -Wno-tabs
  - -Wno-type-defaults
  - -Wno-unused-packages
  - -Wunused-type-patterns
  - -fpedantic-bottoms
  - -feager-blackholing
  - -fexcess-precision
  - -flate-dmd-anal
  - -fregs-iterative
  - -fspecialise-aggressively
  - -flate-specialise
  - -fstatic-argument-transformation

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src

executables:
  snip:
    main: Main.hs
    source-dirs: app
    dependencies:
      - the-snip
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  the-snip-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - the-snip
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
